version: "2"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
